Added release workflow
pybamm-team/pybamm-cookie pull request #48
Opened 2024-08-19 16:19 UTC by santacodes

Added `release.yml` file referred from [PyPI OIDC docs](https://docs.pypi.org/trusted-publishers/).

2024-08-20 00:08 UTC, agriyakhetarpal requested changes
This isn't correct – the PyPI docs are likely truncated and display only a truncated part of what is needed to be added. You'll need to build an sdist and a wheel in one job using `pypa/build` (I like https://github.com/hynek/build-and-inspect-python-package), upload their artifacts, download them in another job, and and trigger the publishing from that job.

Also, you might have done this already, but please ensure that the name of the workflow file matches that set in the PyPI settings for `pybamm-cookie` that you might have set up by now (if you have, please feel free to add us there!) and that the name of the environment you added matches the one in the `environment:` section here, i.e., `release`.

2024-08-22 14:37 UTC, santacodes commented
@agriyakhetarpal @Saransh-cpp sorry for the delay, could you verify if the release workflow is now valid? `pypa/gh-action-pypi-publish@release/v1` action by default looks for the `sdist` and `whl` from the `dist/` directory so a simple `python -m build` should do it I guess?

2024-08-22 14:50 UTC, agriyakhetarpal requested changes
No, this still isn't valid, but the structure is getting towards the right place!
- The idea is to build the sdist and wheel in an entirely separate job, upload them as artifacts (you're right – both can be kept in a `dist/` folder).
- We don't need to set up `uv`, GHA runners come with `pipx` by default, so you can just run `pipx run build` instead of `python -m build`.
- Then, in a separate Ubuntu job, download the artifacts, and grant just that job `id-token: write` permissions – the separation of the jobs is important for security reasons: please read the end of the [Trusted publishing](https://github.com/pypa/gh-action-pypi-publish/tree/release/v1/?tab=readme-ov-file#trusted-publishing) section of the documentation. 

Also, the latest release of `pypa/gh-action-pypi-publish` is v1.9.0, could you update that and set it to point to the hash of the v1.9.0 commit? I'll suggest a change below for it.

2024-08-22 14:50 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +        uses: pypa/gh-action-pypi-publish@release/v1
```suggestion
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0  # v1.9.0
```

2024-08-22 16:28 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +  build-wheels:
```suggestion
  build:
```

2024-08-22 16:28 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +          python-version: 3.12
```suggestion
```

We'll need to keep updating the Python version, so we might as well remove it and let it use the latest available one

2024-08-22 16:28 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +          if-no-files-found: error
```suggestion
          name: sdist_and_wheel
          path: ./dist/*
          if-no-files-found: error
```

`pipx run build` creates both the sdist and the wheel, so why not upload both?

2024-08-22 16:28 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +    needs: [build-wheels]
```suggestion
    needs: [build]
```

2024-08-22 16:28 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +          path: artifacts
```suggestion
        with:
          path: artifacts
          merge-multiple: true
```

This change will cause the artifacts to get downloaded into the `artifacts/` folder, and not inside `artifacts/sdist_and_wheel/`, which should be better.

2024-08-22 16:28 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +    name: upload pybamm-cookie wheel artifacts
```suggestion
    name: Build and pybamm-cookie sdist and wheel
```

2024-08-22 16:28 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +    needs: [build-wheels]
```suggestion
    needs: [build]
```

2024-08-22 16:33 UTC, santacodes commented on .github/workflows/release.yml
> +    needs: [build-wheels]
I guess this suggestion got duplicated

2024-08-22 16:56 UTC, agriyakhetarpal commented on .github/workflows/release.yml
> +    needs: [build-wheels]
Oops, thanks!

2024-08-22 16:56 UTC, agriyakhetarpal approved these changes

2024-08-22 16:57 UTC, agriyakhetarpal commented
Thanks for the fixes, @santacodes! Let's create the release in the meeting in a short while from now.

2024-08-22 17:37 UTC, merged