Added a note in README on managing upstream URLs.
pybamm-team/pybamm-cookie pull request #58
Opened 2024-08-30 12:58 UTC by santacodes

Added a note pointing to the GitHub documentation with instructions on adding an upstream URL to the generated project.

Fixes #35

2024-08-30 16:27 UTC, agriyakhetarpal requested changes
I don't wish to be too nitpicky, but this sentence implies that a remote repository that users can push to already exists on GitHub. Could you please reword this section so that it mentions a link to explain how one can create a GitHub repository and link it with the one that gets created in the directory?

Also, if users were to add a license (and/or a README) to a new repository that they create on GitHub's UI, and then create a Git repository locally to link to it, they could face troubles when they try to push the changes because the remote repository would not be empty. That's something to think about, too, since we can expect some users of the template to be new to both Git as a version control system and to how it interacts with GitHub.

There is also a pathway where they don't have a remote repository at all and they would want to try publishing the one they created locally to GitHub, which requires different steps. All of this information is available in depth in the GitHub documentation, so just linking it together in the right manner should be fine. 👍

2024-08-30 16:27 UTC, agriyakhetarpal commented on README.md
> +> A `git` repository is automatically initialised when a project is created within a directory, to push the contents to upstream GitHub repository, follow these steps in the [GitHub documentation](ht
```suggestion
> A `git` repository is automatically initialised when a project is created within a directory. To push the contents to the upstream GitHub repository, follow these steps as listed in the [GitHub documentation](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#adding-a-remote-repository).
```

2024-08-31 13:51 UTC, santacodes commented
@agriyakhetarpal the new link should cover all the points that you mentioned.

2024-08-31 14:43 UTC, agriyakhetarpal approved these changes
This looks better, thanks, @santacodes!

2024-08-31 15:05 UTC, merged